# Generated by Django 4.1.7 on 2023-03-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_image', models.URLField()),
                ('Product_price', models.CharField(max_length=1000000)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
